version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sergio
      POSTGRES_PASSWORD: sergiopassword
      POSTGRES_DB: mestdb
    ports:
      - 5499:5499